name: Swift
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  build:
    # macos-latest
    runs-on: macos-14
    steps:
      - name: Install Xcode.
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1.7.0
        with:
          # 15.0 / 16-beta etc
          xcode-version: 16.2
      - name: Checkout source.
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive
      - name: Build.
        run: swift build -v
    #   - name: Run tests.
    #     run: swift test -v
